export const siteConfig = {
  name: 'Touchpoint',
  company: 'New Wave Synergy',
  url: 'https://touchpoint.newwavesynergy.com',
  tagline: 'Post-Completion, Handover & Asset Transition Support',
  description:
    'Touchpoint by New Wave Synergy combines hands-on post-completion support, physical inspections, handover coordination and digital asset intelligence to help developers, builders and asset owners move from Practical Completion into occupation and operations.',
  keywords: [
    'post-completion support',
    'physical inspections',
    'handover management',
    'asset transition platform',
    'practical completion',
    'operational readiness',
    'digital asset handover',
    'defect closeout',
    'defect management',
    'construction closeout',
    'facility management software',
    'NFC asset tagging',
    'QR asset tracking',
    'asset lifecycle management',
    'O&M documentation',
    'Australia New Zealand construction technology',
  ],
  locale: 'en_AU',
  parent: {
    name: 'New Wave Synergy',
    url: 'https://www.newwavesynergy.com',
    contactUrl: 'https://www.newwavesynergy.com/contact',
  },
  contact: {
    email: 'naomi@newwavesynergy.com',
    phone: '+61 410 323 102',
    phoneDisplay: '0410 323 102',
    person: 'Naomi Mabvurira',
    role: 'CEO & Founder',
    entity: 'New Wave Synergy Pty Ltd',
    location: 'Australia and New Zealand',
  },
  social: {
    linkedin: 'https://www.linkedin.com/company/new-wave-synergy',
    instagram: 'https://www.instagram.com/touchpoint.synergy',
    instagramHandle: '@touchpoint.synergy',
  },
  nav: [
    { label: 'Who we help', href: '#who-we-help' },
    { label: 'Problem', href: '#problem' },
    { label: 'How it works', href: '#how' },
    { label: 'Support model', href: '#system' },
    { label: 'Pilot', href: '#pilot' },
    { label: 'About', href: '#about' },
    { label: 'Contact', href: '#contact' },
  ],
};

export type SiteConfig = typeof siteConfig;
